### PR TITLE
fix: add missing fields to ChatCompletionChunk 

### LINKED ISSUE #19: The `ChatCompletionChunk` has no `usage` field, but it should have
Usage is very important to know how many tokens were generated per each request. There are other fields missing from the Chat Completions chunk, check the official documentation:

https://docs.atoma.network/cloud-api-reference/chat/create-chat-completion

### PR DESCRIPTION
**Pull request by fishonamos**
closes #19

### CODE REVIEW

File: src/models/components/chatcompletionchunk.ts [hunk 1]
```diff
@@ -30,39 +37,83 @@ export type ChatCompletionChunk = {
...
    */
   model: string;
+  /**
+   * The system fingerprint for the completion
+   */
+  systemFingerprint?: string | null | undefined;
+  /**
+   * Usage statistics for the completion request.
+   */
+  usage?: CompletionUsage | null | undefined;
```
Comment (maschad) [inline src/models/components/chatcompletionchunk.ts:47]: we should also include the `service_tier` and `object` no?

**Review by maschad — CHANGES_REQUESTED** [review]
Nice work, but left a comment.

let's also add a test to ensure these are always returned.

**Comment by fishonamos** [comment]
> Nice work, but left a comment.
> 
> let's also add a test to ensure these are always returned.

I tried to run the test on main branch to see how it works and i get this error.


image

**Review by maschad — APPROVED** [review]
